### PR TITLE
Use JSON.stringify() instead of .join() to avoid key collision

### LINKED ISSUE #9: Joined keys are vulnerable to collision
Pointed out by Bartkus.

Collision: `["a", "_b"]` and `["a_", "b"]`.

One simple solution would be to just `JSON.stringify` instead of joining.

### PR DESCRIPTION
**Pull request by avastu**
Fixes #9.
~~[Edit]: I've also removed the gulp-nsp module. The node security service has [shut down](https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting). The replacement is [npm audit](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities), but the workflow is different, and I think it calls for a separate issue to determine that workflow.~~

### CODE REVIEW

**Comment by gigabo** [comment]
Yep, that'll do it. Thanks @avastu!

This is a breaking change... it will invalidate all existing cache entries.

**Comment by avastu** [comment]
There's a single test failure, which I believe #15 fixes.

**Comment by gigabo** [comment]
> There's a single test failure, which I believe #15 fixes.

Unfortunately #15 is _also_ a breaking change. 😂

**Comment by gigabo** [comment]
Thanks @avastu. Could you do the nsp removal as a separate PR? I want to make sure the build on master fails in the same way as _this_ PR before merge.

**Comment by avastu** [comment]
Definitely!

**Comment by gigabo** [comment]
Hmm... the build passed on master. 😕

**Comment by avastu** [comment]
Must be my fault! I'll take a look now.

**Comment by avastu** [comment]
Sorry for the delay on this! Turns out the test just needed to be updated to use the correct cache key :).

**Comment by gigabo** [comment]
Oh, nice! Glad you got it figured out!

Thanks @avastu!

**Pull request merged**
